Dairy is murder
kokoaespol/Chocolatada pull request #23
Opened 2022-12-11 18:03 UTC by practicatto

2022-12-30 19:05 UTC, adriandelgado requested changes
El component `<Icon />` está diseñado para íconos svg para ponerlos inline en el html. Es una optimización para mejor "performance". Sin embargo, si el svg es grande y complejo, se debería solo usar una `img` tag.

2022-12-30 19:05 UTC, adriandelgado commented on src/routes/+page.svelte
> +<div class="absolute " />
Este elemento se ha colado.

2022-12-30 23:33 UTC, practicatto commented on src/routes/+page.svelte
> +      <Icon data={chocoimagen} width="300" height="400" aria-hidden="true" />
ok entendible

2022-12-30 23:34 UTC, practicatto commented on src/routes/+page.svelte
> +<div class="absolute " />
shiet

2023-01-02 05:30 UTC, adriandelgado approved these changes
LGTM!

2023-01-03 00:01 UTC, merged